export const DIAGNOSTIC_SKILL_KEYS=['leitura','compreensao','escrita','adicao','multiplicacao','divisao','porcentagem','medidas','seguranca','direitos','saude','tecnologia'] as const;
const PRIMARY_IDS=['diag-com-01','diag-com-02','diag-com-03','diag-com-04','diag-com-05','diag-mat-01','diag-mat-02','diag-mat-03','diag-mat-04','diag-mat-05','diag-mat-06','diag-work-01','diag-work-02','diag-work-03','diag-work-04'] as const;
const CONFIRM_IDS=['diag-com-confirm','diag-mat-confirm','diag-work-confirm'] as const;
const QUESTION_IDS=new Set<string>([...PRIMARY_IDS,...CONFIRM_IDS]);
const CONFIRM_SET=new Set<string>(CONFIRM_IDS);
export type DiagnosticAssignment=`level:N${1|2|3|4|5}`;
export type DiagnosticDraftStateV1={version:1;skillIndex:number;level:number;assigned:Record<string,DiagnosticAssignment>};
export type DiagnosticDraftStateV2={version:2;questionIndex:number;responses:Record<string,string>;confirmationIds:string[]};
export type DiagnosticDraftState=DiagnosticDraftStateV1|DiagnosticDraftStateV2;
export type DiagnosticDraft=DiagnosticDraftState&{updatedAt:string};
const isRecord=(value:unknown):value is Record<string,unknown>=>!!value&&typeof value==='object'&&!Array.isArray(value);
const isTimestamp=(value:unknown):value is string=>{if(typeof value!=='string'||!value)return false;const time=Date.parse(value);return Number.isFinite(time)&&new Date(time).toISOString()===value};
const sanitizeV1=(value:Record<string,unknown>):DiagnosticDraftStateV1|null=>{const {skillIndex,level,assigned}=value;if(typeof skillIndex!=='number'||!Number.isInteger(skillIndex)||skillIndex<0||skillIndex>11||typeof level!=='number'||!Number.isInteger(level)||level<1||level>5||!isRecord(assigned))return null;const clean:Record<string,DiagnosticAssignment>={};for(const [skill,assignment] of Object.entries(assigned)){if(!DIAGNOSTIC_SKILL_KEYS.includes(skill as (typeof DIAGNOSTIC_SKILL_KEYS)[number]))return null;if(!/^level:N[1-5]$/.test(String(assignment)))return null;clean[skill]=String(assignment) as DiagnosticAssignment}return{version:1,skillIndex,level,assigned:clean}};
const sanitizeV2=(value:Record<string,unknown>):DiagnosticDraftStateV2|null=>{const {questionIndex,responses,confirmationIds}=value;if(typeof questionIndex!=='number'||!Number.isInteger(questionIndex)||questionIndex<0||questionIndex>18||!isRecord(responses)||!Array.isArray(confirmationIds)||confirmationIds.length>3)return null;const confirms=confirmationIds.map(String);if(new Set(confirms).size!==confirms.length||confirms.some(id=>!CONFIRM_SET.has(id)))return null;const sequence=[...PRIMARY_IDS,...confirms],expected=sequence.slice(0,questionIndex),keys=Object.keys(responses);if(questionIndex>sequence.length||keys.length!==questionIndex||expected.some(id=>!Object.prototype.hasOwnProperty.call(responses,id)))return null;const clean:Record<string,string>={};for(const [id,response] of Object.entries(responses)){if(!QUESTION_IDS.has(id)||typeof response!=='string'||!response.trim()||response.length>1000)return null;clean[id]=response.trim()}return{version:2,questionIndex,responses:clean,confirmationIds:confirms}};
export function sanitizeDiagnosticDraftState(value:unknown):DiagnosticDraftState|null{if(!isRecord(value))return null;if(value.version===1)return sanitizeV1(value);if(value.version===2)return sanitizeV2(value);return null}
export function sanitizeDiagnosticDraft(value:unknown):DiagnosticDraft|null{const state=sanitizeDiagnosticDraftState(value);if(!state||!isRecord(value)||!isTimestamp(value.updatedAt))return null;return{...state,updatedAt:value.updatedAt}}
export function createDiagnosticDraft(value:unknown,updatedAt:string):DiagnosticDraft|null{const state=sanitizeDiagnosticDraftState(value);return state&&isTimestamp(updatedAt)?{...state,updatedAt}:null}
export function canClearDiagnosticDraftAfterFinalization(finalDiagnosticSaved:boolean,participantUpdated:boolean):boolean{return finalDiagnosticSaved&&participantUpdated}
