import {sanitizeDiagnosticDraft,sanitizeDiagnosticDraftState,type DiagnosticDraft,type DiagnosticDraftStateV2,type DiagnosticAssignment} from '../backend/diagnostic-draft';
import {ALL_DIAGNOSTIC_ITEMS,CONFIRMATION_DIAGNOSTIC_ITEMS,DIAGNOSTIC_MAX_COUNT,DIAGNOSTIC_PRIMARY_COUNT,DIAGNOSTIC_SKILLS,PRIMARY_DIAGNOSTIC_ITEMS,diagnosticItemById,type DiagnosticArea,type DiagnosticItem,type DiagnosticSkill} from './diagnostic-bank';
export type DiagnosticFlowState=Omit<DiagnosticDraftStateV2,'version'>;
const norm=(value:string)=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();
export function diagnosticInitialState():DiagnosticFlowState{return{questionIndex:0,responses:{},confirmationIds:[]}}
export function evaluateDiagnosticResponse(item:DiagnosticItem,value:string):boolean{const clean=norm(value);if(item.kind==='choice')return clean===norm(String(item.answer||''));if(item.minLength&&value.trim().length<item.minLength)return false;return(item.requiredTerms||[]).every(term=>clean.includes(norm(term)))}
const areaAccuracy=(area:DiagnosticArea,responses:Record<string,string>)=>{const items=PRIMARY_DIAGNOSTIC_ITEMS.filter(item=>item.area===area),answered=items.filter(item=>responses[item.id]!=null);if(!answered.length)return 0;return answered.filter(item=>evaluateDiagnosticResponse(item,responses[item.id])).length/answered.length};
export function selectDiagnosticConfirmations(responses:Record<string,string>):string[]{const areas:DiagnosticArea[]=['comunicacao','matematica','trabalho'];return areas.filter(area=>{const ratio=areaAccuracy(area,responses);return ratio>=0.2&&ratio<=0.8}).map(area=>CONFIRMATION_DIAGNOSTIC_ITEMS.find(item=>item.area===area)!.id).slice(0,3)}
const sequence=(state:DiagnosticFlowState)=>[...PRIMARY_DIAGNOSTIC_ITEMS,...state.confirmationIds.map(id=>diagnosticItemById(id)).filter((item):item is DiagnosticItem=>!!item)];
export function currentDiagnosticItem(state:DiagnosticFlowState):DiagnosticItem|null{return sequence(state)[state.questionIndex]||null}
export function recordDiagnosticResponse(state:DiagnosticFlowState,value:string):DiagnosticFlowState{const item=currentDiagnosticItem(state);if(!item||state.questionIndex>=DIAGNOSTIC_MAX_COUNT)return state;const responses={...state.responses,[item.id]:value.trim()};let confirmationIds=[...state.confirmationIds];if(state.questionIndex===DIAGNOSTIC_PRIMARY_COUNT-1&&!confirmationIds.length)confirmationIds=selectDiagnosticConfirmations(responses);return{questionIndex:state.questionIndex+1,responses,confirmationIds}}
export function diagnosticIsComplete(state:DiagnosticFlowState):boolean{return state.questionIndex>=sequence(state).length&&Object.keys(state.responses).length>=DIAGNOSTIC_PRIMARY_COUNT}
export function diagnosticProgress(state:DiagnosticFlowState):{label:string;percentage:number;phase:'primary'|'confirmation';position:number;total:number}{if(state.questionIndex<DIAGNOSTIC_PRIMARY_COUNT){const position=state.questionIndex+1;return{label:`Questão ${position} de aproximadamente 15 · máximo 18`,percentage:Math.round(position/DIAGNOSTIC_PRIMARY_COUNT*100),phase:'primary',position,total:DIAGNOSTIC_PRIMARY_COUNT}}const position=state.questionIndex-DIAGNOSTIC_PRIMARY_COUNT+1,total=Math.max(1,state.confirmationIds.length);return{label:`Confirmação rápida ${position} de ${total}`,percentage:Math.round(state.questionIndex/(DIAGNOSTIC_PRIMARY_COUNT+total)*100),phase:'confirmation',position,total}}
export function diagnosticAssignments(state:DiagnosticFlowState):Record<DiagnosticSkill,DiagnosticAssignment>{const evidence=new Map<DiagnosticSkill,number[]>();DIAGNOSTIC_SKILLS.forEach(skill=>evidence.set(skill,[]));for(const item of ALL_DIAGNOSTIC_ITEMS){const value=state.responses[item.id];if(value==null)continue;const level=evaluateDiagnosticResponse(item,value)?item.passLevel:item.missLevel;item.skills.forEach(skill=>evidence.get(skill)!.push(level))}return Object.fromEntries(DIAGNOSTIC_SKILLS.map(skill=>{const values=evidence.get(skill)||[],avg=values.length?values.reduce((a,b)=>a+b,0)/values.length:2,level=Math.max(1,Math.min(5,Math.round(avg)));return[skill,`level:N${level}` as DiagnosticAssignment]})) as Record<DiagnosticSkill,DiagnosticAssignment>}
const parseLevel=(value:string)=>Number(value.match(/N([1-5])/)?.[1]||2);
export function diagnosticAreaSummary(skillLevels:Record<string,string>){const areas=[{id:'comunicacao',label:'Capacitação em Comunicação',skills:['leitura','compreensao','escrita']},{id:'matematica',label:'Capacitação Matemática',skills:['adicao','multiplicacao','divisao','porcentagem','medidas']},{id:'trabalho',label:'Capacitação para o Trabalho',skills:['seguranca','direitos','saude','tecnologia']}];return areas.map(area=>{const avg=area.skills.reduce((sum,skill)=>sum+parseLevel(String(skillLevels[skill]||'N2')),0)/area.skills.length,label=avg<=2?'Base inicial':avg<=3.5?'Em desenvolvimento':'Bom domínio';return{area:area.id,title:area.label,label}})}
export function applyLoadedDiagnosticDraft(fallback:DiagnosticFlowState,loaded:unknown):DiagnosticFlowState{const draft=sanitizeDiagnosticDraft(loaded);return draft?.version===2?{questionIndex:draft.questionIndex,responses:{...draft.responses},confirmationIds:[...draft.confirmationIds]}:{questionIndex:fallback.questionIndex,responses:{...fallback.responses},confirmationIds:[...fallback.confirmationIds]}}
export function diagnosticDraftPayload(state:DiagnosticFlowState):DiagnosticDraftStateV2|null{const parsed=sanitizeDiagnosticDraftState({version:2,...state});return parsed?.version===2?parsed:null}
export function isLegacyDiagnosticDraft(loaded:unknown):boolean{return sanitizeDiagnosticDraft(loaded)?.version===1}
export {DIAGNOSTIC_MAX_COUNT,DIAGNOSTIC_PRIMARY_COUNT};
export type {DiagnosticDraft};
