export type TeachingSource={objective:string;context:string;material:string};
export type TeachingPart={title:string;eyebrow:string;body:string;example:string;check:string};
export type TeachingSequence={part1:TeachingPart;part2:TeachingPart;reinforcement:TeachingPart};

const GUIDES:Record<string,{foundation:string;practice:string;mistake:string;example:string}>={
leitura:{foundation:'Leia uma informação por vez. Procure palavras de ação, horário, local, quantidade e ordem antes de interpretar o restante.',practice:'Na prática, compare o que o texto realmente diz com o que você imaginou. Marque primeiro a informação explícita e só depois faça inferências.',mistake:'Não complete o texto com informações que não aparecem nele.',example:'Em “Entrega às 14h na sala 2”, as informações verificáveis são horário e local.'},
compreensao:{foundation:'Compreender é ligar as informações do texto sem inventar dados. Identifique a ideia principal e a relação entre causa, consequência, ordem ou finalidade.',practice:'Explique a resposta usando uma pista concreta do texto. Quando houver duas mensagens, compare o que muda e o que permanece igual.',mistake:'Evite escolher uma alternativa apenas porque parece provável; procure evidência no enunciado.',example:'Se o material acabou antes do fim do serviço, a consequência direta é precisar repor ou reorganizar a atividade.'},
escrita:{foundation:'Uma mensagem funcional precisa dizer o que aconteceu, onde ou quando for necessário, e qual ação é esperada. Prefira frases curtas e específicas.',practice:'Depois de escrever, releia como se outra pessoa recebesse a mensagem sem contexto. Confira se ela saberia o que ocorreu e o que fazer.',mistake:'Evite expressões vagas como “deu problema” ou “aquela coisa”.',example:'“12/03 · almoxarifado · faltaram 4 conexões” é mais útil do que “faltou material”.'},
adicao:{foundation:'Adição junta quantidades e subtração mostra o que resta ou a diferença. Antes da conta, identifique o valor inicial e o que entrou ou saiu.',practice:'Organize os dados na ordem em que aconteceram e confira se o resultado faz sentido para a situação.',mistake:'Não some quando o enunciado descreve retirada, uso ou diferença.',example:'Havia 18 peças e chegaram 7: 18 + 7 = 25.'},
multiplicacao:{foundation:'Multiplicação representa grupos iguais. Descubra quantos grupos existem e quantos itens há em cada grupo.',practice:'Use a multiplicação para evitar somas repetidas e confira o resultado estimando a quantidade total.',mistake:'Não multiplique valores que não representam grupos equivalentes.',example:'4 caixas com 6 peças cada: 4 × 6 = 24.'},
divisao:{foundation:'Divisão reparte uma quantidade em partes iguais ou descobre quantos grupos cabem no total. Identifique o total e por quantos grupos ele será repartido.',practice:'Depois de dividir, confira multiplicando a resposta pelo número de grupos. Se houver resto, observe se a situação permite sobra.',mistake:'Não troque total por quantidade de grupos.',example:'24 peças para 6 pessoas: 24 ÷ 6 = 4 para cada pessoa.'},
porcentagem:{foundation:'Porcentagem é uma parte de 100. Primeiro identifique o valor total e depois a taxa solicitada.',practice:'Use referências simples como 10%, 25% e 50% e confira se o resultado é coerente: uma parte não pode superar o todo sem motivo.',mistake:'Não confunda 10% com 10 unidades.',example:'10% de 200 = 20.'},
medidas:{foundation:'Antes de calcular, identifique a grandeza e a unidade: metro, centímetro, litro, hora ou outra medida. Conversões exigem manter a mesma grandeza.',practice:'Escreva a unidade junto do resultado e faça uma estimativa para perceber erros de escala.',mistake:'Não compare números de unidades diferentes sem converter.',example:'2 m = 200 cm.'},
seguranca:{foundation:'Leia o cenário, identifique o risco imediato e escolha uma ação que reduza a exposição e permita comunicação responsável.',practice:'Priorize medidas preventivas e registros claros antes de retomar a atividade.',mistake:'Não normalize uma condição de risco só porque ainda não ocorreu acidente.',example:'Área escorregadia: sinalizar, controlar o acesso e comunicar o responsável.'},
direitos:{foundation:'Situações de trabalho precisam ser analisadas com informação clara, respeito e registro. Quando houver dúvida, confirme a orientação e o canal correto.',practice:'Compare fatos, responsabilidades e registros antes de concluir ou encaminhar uma situação.',mistake:'Evite decisões baseadas apenas em boatos ou lembranças incompletas.',example:'Uma orientação confusa deve ser esclarecida e confirmada antes da execução.'},
saude:{foundation:'Observe sinais do corpo e do ambiente. Quando houver mal-estar ou exposição inadequada, a prioridade é interromper com segurança e buscar apoio.',practice:'Relacione causa, consequência e prevenção, registrando o que ocorreu quando necessário.',mistake:'Não esconda sintomas nem mantenha exposição apenas para terminar a tarefa.',example:'Tontura no calor: parar com segurança, hidratar quando adequado e comunicar.'},
tecnologia:{foundation:'Antes de clicar, enviar ou compartilhar, confira a origem da informação e proteja dados pessoais e credenciais.',practice:'Use nomes, datas, permissões e fontes para que o registro digital possa ser conferido depois.',mistake:'Urgência não é motivo para enviar senha ou dado sensível sem verificar a origem.',example:'Link desconhecido pedindo senha: não informar e confirmar a origem por canal confiável.'}
};

const LEVEL:Record<string,{focus:string;practice:string}>={
N1:{focus:'Comece reconhecendo uma informação ou operação de cada vez.',practice:'Faça a sequência com apoio e confira o passo básico antes de continuar.'},
N2:{focus:'Conecte duas informações diretas e transforme a regra em uma ação simples.',practice:'Resolva situações curtas e explique para si mesmo o que mudou.'},
N3:{focus:'Aplique o conteúdo em situações da rotina, escolhendo a estratégia adequada.',practice:'Compare a resposta com o contexto para verificar se ela é plausível.'},
N4:{focus:'Analise mais de uma condição, organize etapas e compare alternativas.',practice:'Justifique a escolha usando dados do enunciado e uma conferência final.'},
N5:{focus:'Planeje e decida com autonomia, usando evidências e revisão do próprio raciocínio.',practice:'Teste a solução, identifique limites e registre por que ela é adequada.'}
};

const compact=(parts:string[])=>parts.map(x=>x.trim()).filter(Boolean).join(' ');
export function buildTeachingSequence(unitId:string,source:TeachingSource):TeachingSequence{
 const match=unitId.match(/^(.*)-(N[1-5])$/),skill=match?.[1]||'leitura',level=match?.[2]||'N1',guide=GUIDES[skill]||GUIDES.leitura,lvl=LEVEL[level]||LEVEL.N1;
 const part1:TeachingPart={eyebrow:'CONTEÚDO DA AULA',title:'Entenda antes de praticar',body:compact([source.context,lvl.focus,guide.foundation]),example:guide.example,check:'Ao terminar, você deve conseguir identificar a informação principal e explicar qual estratégia usará.'};
 const part2:TeachingPart={eyebrow:'APLICAÇÃO',title:'Aplique e confira',body:compact([guide.practice,lvl.practice,'Objetivo desta etapa: '+source.objective]),example:'Atenção a um erro comum: '+guide.mistake,check:'Antes de responder, identifique os dados, escolha a estratégia e faça uma conferência rápida.'};
 const reinforcement:TeachingPart={eyebrow:'REFORÇO RÁPIDO',title:'Vamos olhar de outro jeito',body:compact(['Volte ao ponto central.',guide.foundation,'Agora faça uma coisa de cada vez e verbalize o que cada dado significa.']),example:guide.example,check:'Resolva as próximas questões sem pressa; o objetivo é entender o caminho, não responder rápido.'};
 return{part1,part2,reinforcement};
}
