import { auth, api } from '@appdeploy/client';
import { renderManagementDashboard, managementHtml } from './mobile-dashboard';
import './styles.css';

type Role = 'admin' | 'foreman' | 'employee';
type Bootstrap = {
  needsClaim: boolean;
  authorized?: boolean;
  isOwner?: boolean;
  license?: { modules?:string[]; channels?:string[]; status?:string; expiresAt?:string } | null;
  role?: Role;
  membership?: { projectId:string; companyId:string; employeeId?:string; email?:string; modules?:string[]; channels?:string[] };
  access?: { modules:string[]; channels:string[]; status:string; expiresAt?:string };
  project?: { id?:string; name?:string; customer?:string };
  company?: { id?:string; name?:string };
  projectInitialized?: boolean;
  user?: { userId:string; email?:string; name?:string };
};
type Member = { id:string; email:string; name?:string; role:Role; employeeId?:string; userId?:string; joinCode?:string; modules?:string[]; channels?:string[] };
type Task = { id:string; date:string; service:string; floor:number; startTime:string; note?:string; source:string };
type ProjectState = Record<string, unknown> & { employees?: Array<Record<string, unknown>> };
type ApiLike = typeof api;
type AuthLike = typeof auth;

declare global {
  interface Window {
    appClient: { auth: AuthLike; api: ApiLike };
    multiuserContext?: { role:Role; bootstrap:Bootstrap; projectState?:ProjectState; online:boolean };
    multiuserSync?: (state:ProjectState)=>void;
    multiuserAttendance?: (employeeId:string,status:string)=>Promise<{day:Record<string,unknown>;employee:Record<string,unknown>}>;
    multiuserInjectAdminSettings?: ()=>void;
    multiuserOpenUsers?: ()=>void;
    multiuserReloadProject?: ()=>Promise<ProjectState>;
    mobileBridgeUpdate?: (payload:Record<string,unknown>)=>Promise<any>;
    mobileResolveConflict?: (conflictId:string,resolution:'accept_desktop'|'keep_mobile')=>Promise<any>;
    mobileReadOnlySummary?: any;
    mobileSyncConflicts?: any[];
    mobileManagementHtml?: (summary:any,access:any)=>string;
  }
}

window.appClient={auth,api};
let activeBootstrap:Bootstrap|undefined;
const root=()=>document.getElementById('content') as HTMLElement;
const nav=()=>document.querySelector('.nav') as HTMLElement;
const roleLabel=(r:Role)=>r==='admin'?'Admin':r==='foreman'?'Encarregado':'Funcionário';
const serviceLabel=(s:string)=>({corte:'Corte',fixacao:'Fixação',chumbamento:'Chumbamento',afaq:'AF/AQ',esgoto:'Esgoto aéreo',dreno:'Dreno'} as Record<string,string>)[s]||s;
const floorLabel=(n:number)=>n===0?'Térreo':n===-1?'Subsolo 1':n===-2?'Subsolo 2':`${n}º`;
const dateBR=(v:string)=>{const [y,m,d]=v.split('-');return `${d}/${m}/${y}`};
const localISODate=()=>{const d=new Date(),z=d.getTimezoneOffset();return new Date(d.getTime()-z*60000).toISOString().slice(0,10)};
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c] as string));
const DB='fluxodre-campo-standalone';
type AppMode='auto'|'obra'|'gestao';
const routeMode=():AppMode=>location.hash.startsWith('#gestao')?'gestao':location.hash.startsWith('#obra')?'obra':'auto';
function setProjectIdentity(b?:Bootstrap){const title=document.querySelector('.top h1') as HTMLElement|null;if(title)title.textContent=b?.project?.name||'Obra';document.title=b?.project?.name?`FluxoDRE Campo · ${b.project.name}`:'FluxoDRE Campo'}

function openDb():Promise<IDBDatabase>{return new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('kv'))r.result.createObjectStore('kv')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function readLocalState():Promise<ProjectState|null>{try{const db=await openDb(),tx=db.transaction('kv','readonly'),r=tx.objectStore('kv').get('state');return await new Promise((ok,no)=>{r.onsuccess=()=>ok((r.result as ProjectState)||null);r.onerror=()=>no(r.error)})}catch{return null}}
async function writeLocalState(value:ProjectState){try{const db=await openDb(),tx=db.transaction('kv','readwrite');tx.objectStore('kv').put(structuredClone(value),'state')}catch{localStorage.setItem(DB,JSON.stringify(value))}}

function seedState(b?:Bootstrap):ProjectState{
  const services=['corte','fixacao','chumbamento','afaq','esgoto','dreno'];
  const labels:Record<string,string>={corte:'Corte',fixacao:'Fixação',chumbamento:'Chumbamento',afaq:'AF/AQ',esgoto:'Esgoto aéreo',dreno:'Dreno'};
  const employees:Array<Record<string,unknown>>=[];

  const floors=[0,1].map(number=>({number,stages:services.map(service=>({service,label:labels[service],status:'not_started',targetDate:null,checklist:[]}))}));
  const firstDay=localISODate(),day={date:firstDay,presentCount:0,absentCount:0,attendance:{},assignments:[],events:[],note:'',plans:[],sessions:[]};
  return{version:6,project:{name:b?.project?.name||'Nova obra',customer:b?.project?.customer||'',startFloor:0,targetFloor:1},settings:{defaultWorkStart:'07:30',marginalEfficiency:.7,averageWeeklyAbsences:2,unassignedCompensationDays:3,attendanceTimesheetMode:'disabled'},employees,floors,days:{[firstDay]:day},checklistTemplates:{},issues:[],history:[]};
}

function setHeader(role?:Role,online=true){const indicator=document.querySelector('.local') as HTMLElement|null;if(!indicator)return;if(!role){indicator.innerHTML='<i></i> Login';return}indicator.innerHTML=`<i></i>${roleLabel(role)} · ${online?'Online':'Offline'}`;indicator.setAttribute('role','button');indicator.tabIndex=0;indicator.onclick=()=>openAccount(role,online)}
function openOwnerPortal(){location.hash='#owner';location.reload()}function openAccount(role:Role,online:boolean){const dlg=document.getElementById('sheet') as HTMLDialogElement,owner=activeBootstrap?.isOwner===true;dlg.innerHTML=`<div class="sheet"><div class="sheet-head"><div><h2>Minha conta</h2><div class="meta">${roleLabel(role)} · ${online?'sincronizado':'modo local'}</div></div><button class="close">×</button></div>${owner?'<button id="ownerPortalBtn" class="btn" style="width:100%;margin-top:14px">Central de Licenças / Comercial</button><div class="meta">Libere clientes, planos, módulos, links e computadores autorizados.</div>':''}<button id="signOutBtn" class="linkbtn" style="width:100%;margin-top:14px">Sair da conta</button></div>`;dlg.showModal();dlg.querySelector('.close')?.addEventListener('click',()=>dlg.close());dlg.querySelector('#ownerPortalBtn')?.addEventListener('click',openOwnerPortal);dlg.querySelector('#signOutBtn')?.addEventListener('click',async()=>{await auth.signOut();location.reload()})}
function messageCard(title:string,text:string){return `<div class="card"><strong>${esc(title)}</strong><p class="meta">${esc(text)}</p></div>`}

function renderLogin(){nav().style.display='none';setHeader();root().innerHTML=`<section class="auth-page"><div class="auth-card"><small>FluxoDRE Campo</small><h2>Gestão da obra em equipe</h2><p>Entre para acessar a obra conforme seu perfil: Admin, Encarregado ou Funcionário.</p><button id="loginBtn" class="btn auth-btn">Entrar</button><p class="meta">Se esta for sua primeira conta, você poderá criar a empresa e a obra e migrar os dados que já estão neste aparelho.</p></div></section>`;document.getElementById('loginBtn')?.addEventListener('click',signIn)}
async function signIn(){try{await auth.signIn({scope:'openid email profile offline_access'});await start()}catch(e){const code=(e as {code?:string}).code;const txt=code==='popup_blocked'?'Permita pop-ups para fazer login.':code==='popup_closed'?'Login cancelado.':'Não foi possível entrar.';showStandalone(txt)}}async function mountDesktopAuth(){nav().style.display='none';setHeader();const raw=location.hash.slice('#desktop-auth='.length),pair=raw.split('&')[0].split('.'),requestId=pair[0]||'',secret=pair.slice(1).join('.')||'';if(!requestId||!secret){root().innerHTML=messageCard('Vínculo inválido','Abra novamente o login pelo FLUXODRE Desktop.');return}if(!auth.isSignedIn()){root().innerHTML='<section class="auth-page"><div class="auth-card"><small>FLUXODRE Desktop</small><h2>Autorizar este computador</h2><p>Entre com a mesma conta Google autorizada na sua licença.</p><button id="desktopLoginBtn" class="btn auth-btn">Continuar com Google</button></div></section>';document.getElementById('desktopLoginBtn')?.addEventListener('click',async()=>{try{await auth.signIn({scope:'openid email profile offline_access'});await mountDesktopAuth()}catch(e){showStandalone(apiError(e))}});return}try{const result=(await api.post('/api/desktop/approve',{requestId,secret})).data as {device?:{name?:string}};root().innerHTML=`<section class="auth-page"><div class="auth-card"><small>FLUXODRE Desktop</small><h2>Computador autorizado</h2><p>${esc(result.device?.name||'Este computador')} foi vinculado à sua conta. Você já pode voltar ao aplicativo.</p><div class="card notice"><b>✓</b><div><strong>Autorização concluída</strong><div class="meta">Nenhuma senha Google é armazenada no Desktop.</div></div></div></div></section>`}catch(e){root().innerHTML=`<section class="auth-page"><div class="auth-card"><h2>Não foi possível autorizar</h2><p>${esc(apiError(e))}</p><button id="desktopRetry" class="btn">Tentar novamente</button></div></section>`;document.getElementById('desktopRetry')?.addEventListener('click',()=>void mountDesktopAuth())}}
function showStandalone(text:string){let el=document.getElementById('toast');if(!el){el=document.createElement('div');el.id='toast';el.className='toast';document.body.appendChild(el)}el.textContent=text;el.classList.add('show');setTimeout(()=>el?.classList.remove('show'),2600)}

async function fetchBootstrap():Promise<Bootstrap>{return (await api.get('/api/bootstrap')).data as Bootstrap}
function renderClaim(b:Bootstrap){nav().style.display='none';setHeader();const canCreate=b.authorized===true;root().innerHTML=`<section class="auth-page"><div class="auth-card"><small>Primeiro acesso</small><h2>Ativar FLUXODRE</h2><p>O login identifica sua conta, mas o acesso ao sistema precisa estar liberado.</p><div class="form"><label>Código de acesso ou ativação<input id="joinCode" maxlength="12" autocomplete="one-time-code" placeholder="Código recebido na compra"></label></div><button id="joinBtn" class="btn auth-btn">Ativar acesso</button>${canCreate?`<div class="auth-divider"><span>licença autorizada</span></div><h3>Cadastrar minha operação</h3><p class="meta">Módulos liberados: ${esc((b.license?.modules||[]).join(' · ')||'licença completa')}.</p><div class="form"><label>Empresa<input id="companyName" placeholder="Sua empresa"></label><label>Obra<input id="projectName" placeholder="Primeira obra"></label><label>Cliente<input id="customerName" placeholder="Cliente da obra"></label></div><button id="claimBtn" class="linkbtn auth-btn">Criar empresa e obra</button>`:'<div class="card notice"><b>i</b><div><strong>Conta ainda não liberada</strong><div class="meta">Use o código/link único recebido ou peça a liberação do seu e-mail.</div></div></div>'}</div></section>`;document.getElementById('joinBtn')?.addEventListener('click',async()=>{const code=(document.getElementById('joinCode') as HTMLInputElement).value.trim().toUpperCase();if(!code)return showStandalone('Informe o código de acesso.');try{try{await api.post('/api/access/claim',{code})}catch{await api.post('/api/license/claim',{code})}await start()}catch(e){showStandalone(apiError(e))}});document.getElementById('claimBtn')?.addEventListener('click',async()=>{const companyName=(document.getElementById('companyName') as HTMLInputElement).value.trim(),projectName=(document.getElementById('projectName') as HTMLInputElement).value.trim(),customer=(document.getElementById('customerName') as HTMLInputElement).value.trim();if(!companyName||!projectName)return showStandalone('Informe empresa e obra.');try{await api.post('/api/bootstrap/claim',{companyName,projectName,customer});await start()}catch(e){showStandalone(apiError(e))}})}
function apiError(e:unknown){const x=e as {response?:{data?:{error?:string;message?:string}};message?:string};return x.response?.data?.error||x.response?.data?.message||x.message||'Não foi possível concluir a operação.'}

async function renderMigration(b:Bootstrap){nav().style.display='none';setHeader('admin',true);const local=await readLocalState();const employeeCount=Array.isArray(local?.employees)?local!.employees!.length:0;root().innerHTML=`<section class="auth-page"><div class="auth-card"><small>${esc(b.project?.name||'Obra')}</small><h2>Ativar dados compartilhados</h2><p>A obra foi criada. Agora escolha como iniciar o banco central.</p>${messageCard('Dados neste aparelho',`${employeeCount} funcionário(s) detectados. O arquivo local será preservado como segurança.`)}<button id="migrateBtn" class="btn auth-btn">Migrar dados deste aparelho</button><button id="freshBtn" class="linkbtn auth-btn">Iniciar com estrutura padrão</button></div></section>`;document.getElementById('migrateBtn')?.addEventListener('click',()=>importLocal(local||seedState(b)));document.getElementById('freshBtn')?.addEventListener('click',()=>importLocal(seedState(b)))}
async function importLocal(snapshot:ProjectState){try{const normalized={...snapshot,version:6};await api.post('/api/project/import',{state:normalized});await start();showStandalone('Dados migrados para a obra compartilhada.')}catch(e){showStandalone(apiError(e))}}

let syncTimer:number|undefined;
function configureSharedContext(role:Role,b:Bootstrap,state?:ProjectState){window.multiuserContext={role,bootstrap:b,projectState:state,online:true};window.multiuserSync=(next)=>{if(role!=='admin')return;window.clearTimeout(syncTimer);syncTimer=window.setTimeout(async()=>{try{await api.put('/api/project/state',{state:next});const ctx=window.multiuserContext;if(ctx){ctx.projectState=next;ctx.online=true}setHeader(role,true)}catch{const ctx=window.multiuserContext;if(ctx)ctx.online=false;setHeader(role,false);showStandalone('Salvo no aparelho. Sincronização pendente.')}},650)};window.multiuserAttendance=async(employeeId,status)=>{const res=await api.post('/api/attendance',{date:localISODate(),employeeId,status});return res.data as {day:Record<string,unknown>;employee:Record<string,unknown>}};window.multiuserReloadProject=async()=>{const res=await api.get('/api/project',{date:localISODate()}),next=(res.data as {state:ProjectState}).state;await writeLocalState(next);if(window.multiuserContext)window.multiuserContext.projectState=next;return next};window.mobileBridgeUpdate=async(payload)=>{const res=await api.post('/api/mobile/bridge/update',payload);return res.data};window.mobileResolveConflict=async(conflictId,resolution)=>{const res=await api.post('/api/mobile/sync/conflicts/resolve',{conflictId,resolution});try{window.mobileSyncConflicts=((await api.get('/api/mobile/sync/conflicts')).data as {conflicts:any[]}).conflicts||[]}catch{}return res.data};window.mobileManagementHtml=(summary,access)=>managementHtml(summary,access);window.multiuserInjectAdminSettings=injectAdminSettings;window.multiuserOpenUsers=openUsers}

function activateRoleUI(role:Role){
  const apply=()=>{
    if(role==='admin'){
      const h=Array.from(document.querySelectorAll('.section-head h2')).find(x=>x.textContent?.trim()==='Configurações');
      if(h)window.multiuserInjectAdminSettings?.();
      return;
    }
    document.querySelectorAll('[data-screen="settings"],[data-screen="more"],[data-screen="issues"],[data-screen="management"],#newPlan,#newSession,#saveDayNote,.plan-delete,.plan-start,#compensate,.session-actions').forEach(el=>(el as HTMLElement).style.display='none');
    document.querySelectorAll('.front-select').forEach(el=>{(el as HTMLSelectElement).disabled=true});
    const note=document.getElementById('dayNote') as HTMLTextAreaElement|null;if(note)note.disabled=true;
    const dlg=document.getElementById('sheet');if(dlg?.hasAttribute('open')){dlg.querySelectorAll('input[type="checkbox"]').forEach(el=>{(el as HTMLInputElement).disabled=true});const complete=dlg.querySelector('#complete') as HTMLElement|null;if(complete)complete.style.display='none'}
  };
  apply();new MutationObserver(apply).observe(document.body,{childList:true,subtree:true});
  document.addEventListener('click',e=>{if(role==='admin')return;const t=e.target as Element|null;if(!t)return;const forbidden=t.closest('[data-screen="settings"],[data-screen="more"],[data-screen="issues"],[data-screen="management"],#newPlan,#newSession,.plan-delete,.plan-start,#compensate,.session-actions');if(forbidden){e.preventDefault();e.stopImmediatePropagation();showStandalone('Acesso não permitido para este perfil.')}},true);
}

async function loadSharedApp(b:Bootstrap){const role=b.role as Role;const response=await api.get('/api/project',{date:localISODate()});const remote=(response.data as {state:ProjectState}).state;await writeLocalState(remote);configureSharedContext(role,b,remote);window.mobileReadOnlySummary=null;window.mobileSyncConflicts=[];if(role==='admin'){try{window.mobileReadOnlySummary=((await api.get('/api/mobile/summary')).data as {summary:any}).summary}catch{}try{window.mobileSyncConflicts=((await api.get('/api/mobile/sync/conflicts')).data as {conflicts:any[]}).conflicts||[]}catch{}}setHeader(role,true);nav().style.display='grid';activateRoleUI(role);const fieldModule='/field.js?v=20260820-6';await import(/* @vite-ignore */ fieldModule)}
async function loadManagementOnly(b:Bootstrap){nav().style.display='none';if(b.role!=='admin'){setHeader(b.role,true);root().innerHTML=messageCard('Sem operação mobile','Seu perfil não possui Obra360 e os painéis administrativos móveis são exclusivos do Admin.');return}setHeader('admin',true);try{const data=(await api.get('/api/mobile/summary')).data as {summary:any};renderManagementDashboard(root(),data.summary||{},b.access||{},'Gestão')}catch(e){root().innerHTML=messageCard('Gestão mobile',apiError(e))}}

function injectAdminSettings(){if(window.multiuserContext?.role!=='admin')return;const content=root();if(document.getElementById('multiuserAdminCard'))return;const section=document.createElement('section'),owner=activeBootstrap?.isOwner===true;section.id='multiuserAdminCard';section.className='card settings-card';section.innerHTML=`<div class="section-head"><div><strong>Usuários</strong><p>Administre quem acessa esta obra e o que cada perfil pode fazer.</p></div></div><button id="openUsersBtn" class="btn">Gerenciar usuários</button><div class="meta">Admin: tudo · Encarregado: operação e presença · Funcionário: somente suas tarefas.</div>${owner?'<div style="border-top:1px solid var(--line);margin-top:16px;padding-top:16px"><strong>Comercial FLUXODRE</strong><div class="meta">Área exclusiva do proprietário para vendas e licenças.</div><button id="openOwnerPortalBtn" class="linkbtn" style="width:100%;margin-top:10px">Central de Licenças / Comercial</button></div>':''}`;content.appendChild(section);section.querySelector('#openUsersBtn')?.addEventListener('click',openUsers);section.querySelector('#openOwnerPortalBtn')?.addEventListener('click',openOwnerPortal)}
async function openUsers(){if(window.multiuserContext?.role!=='admin')return showStandalone('Acesso não permitido para este perfil.');const dlg=document.getElementById('sheet') as HTMLDialogElement;dlg.innerHTML='<div class="sheet"><div class="sheet-head"><div><h2>Usuários</h2><div class="meta">Carregando acessos...</div></div><button class="close">×</button></div></div>';dlg.showModal();dlg.querySelector('.close')?.addEventListener('click',()=>dlg.close());try{const [{data},local]=await Promise.all([api.get('/api/members'),readLocalState()]);const members=(data as {members:Member[]}).members||[],employees=(local?.employees||[]) as Array<Record<string,unknown>>;dlg.innerHTML=`<div class="sheet"><div class="sheet-head"><div><h2>Usuários</h2><div class="meta">Acessos desta obra</div></div><button class="close">×</button></div><div class="members-list">${members.map(m=>`<div class="card member-row"><div><strong>${esc(m.email)}</strong><div class="meta">${roleLabel(m.role)}${m.employeeId?` · ${esc(String(employees.find(e=>e.id===m.employeeId)?.name||m.employeeId))}`:''} · ${m.userId?'Ativo':`Aguardando login · Código ${esc(m.joinCode||'—')}`}</div></div></div>`).join('')}</div><div class="form member-form"><label>Email<input id="memberEmail" type="email" placeholder="nome@empresa.com"></label><label>Papel<select id="memberRole"><option value="employee">Funcionário</option><option value="foreman">Encarregado</option><option value="admin">Admin</option></select></label><label id="employeeLinkLabel">Vincular ao funcionário<select id="memberEmployee"><option value="">Selecione</option>${employees.map(e=>`<option value="${esc(e.id)}">${esc(e.name)}</option>`).join('')}</select></label></div><button id="saveMemberBtn" class="btn">Salvar acesso</button></div>`;dlg.querySelector('.close')?.addEventListener('click',()=>dlg.close());const role=dlg.querySelector('#memberRole') as HTMLSelectElement,link=dlg.querySelector('#employeeLinkLabel') as HTMLElement;const toggle=()=>{link.style.display=role.value==='employee'?'block':'none'};role.addEventListener('change',toggle);toggle();dlg.querySelector('#saveMemberBtn')?.addEventListener('click',async()=>{const email=(dlg.querySelector('#memberEmail') as HTMLInputElement).value.trim(),r=role.value as Role,employeeId=(dlg.querySelector('#memberEmployee') as HTMLSelectElement).value||undefined;try{await api.post('/api/members',{email,role:r,employeeId});showStandalone('Acesso salvo.');await openUsers()}catch(e){showStandalone(apiError(e))}})}catch(e){showStandalone(apiError(e))}}

function renderWorker(b:Bootstrap,tasks:Task[],employee:{name?:string},project:{name?:string}){nav().style.display='none';configureSharedContext('employee',b);setHeader('employee',true);const today=localISODate(),todayTasks=tasks.filter(t=>t.date===today),next=tasks.filter(t=>t.date!==today);const cards=(arr:Task[])=>arr.length?arr.map(t=>`<div class="card task-card"><div class="row"><div><strong>${esc(serviceLabel(t.service))} · ${floorLabel(Number(t.floor))}</strong><div class="meta">${dateBR(t.date)} · ${esc(t.startTime||'07:30')}</div>${t.note?`<div class="meta">${esc(t.note)}</div>`:''}</div><span class="badge released">Atribuição</span></div></div>`).join(''):'<div class="empty card">Nenhuma atribuição.</div>';root().innerHTML=`<div class="worker-head"><small>${esc(project.name||'Obra')}</small><h2>Olá, ${esc(employee.name||'')}</h2><p>Estas são somente as suas atribuições.</p></div><section class="section"><div class="section-head"><div><h2>Hoje</h2><p>${dateBR(today)} · início padrão 07:30</p></div></div>${cards(todayTasks)}</section><section class="section"><div class="section-head"><div><h2>Minha semana</h2><p>Próximos dias</p></div></div>${cards(next)}</section>`}
async function loadWorker(b:Bootstrap){try{const data=(await api.get('/api/my-tasks',{today:localISODate()})).data as {tasks:Task[];employee:{name?:string};project:{name?:string}};renderWorker(b,data.tasks||[],data.employee||{},data.project||{})}catch(e){root().innerHTML=messageCard('Acesso do funcionário',apiError(e));setHeader('employee',true)}}

async function start(mode:AppMode=routeMode()){if(!auth.isSignedIn()){renderLogin();return}const user=await auth.getUser();if(!user){renderLogin();return}try{let b=await fetchBootstrap();const activation=location.hash.startsWith('#activate=')?location.hash.slice(10).trim().toUpperCase():'';if(b.needsClaim&&activation){try{await api.post('/api/license/claim',{code:activation});history.replaceState(null,'',location.pathname);b=await fetchBootstrap()}catch(e){showStandalone(apiError(e))}}activeBootstrap=b;setProjectIdentity(b);if(b.needsClaim){renderClaim(b);return}if(!b.access?.channels?.includes('mobile')){nav().style.display='none';root().innerHTML=messageCard('Mobile não contratado','Esta conta não possui acesso ao FLUXODRE Mobile/PWA.');return}if(mode==='gestao'){await loadManagementOnly(b);return}if(!b.access?.modules?.includes('obra360')){await loadManagementOnly(b);return}if(!b.projectInitialized){if(b.role==='admin')await renderMigration(b);else{nav().style.display='none';setHeader(b.role,true);root().innerHTML=messageCard('Obra em preparação','O Admin ainda precisa migrar ou inicializar os dados desta obra.')}return}if(b.role==='employee'){await loadWorker(b);return}await loadSharedApp(b)}catch(e){nav().style.display='none';root().innerHTML=`<section class="auth-page"><div class="auth-card"><h2>Não foi possível carregar a obra</h2><p>${esc(apiError(e))}</p><button id="retryBtn" class="btn">Tentar novamente</button><button id="logoutBtn" class="linkbtn">Sair</button></div></section>`;document.getElementById('retryBtn')?.addEventListener('click',start);document.getElementById('logoutBtn')?.addEventListener('click',async()=>{await auth.signOut();location.reload()})}}

if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{}));
if(location.hash.startsWith('#universidade')){void import('./university').then(m=>m.mountUniversity())}else if(location.hash==='#owner'){void import('./owner').then(m=>m.mountOwnerPortal())}else if(location.hash.startsWith('#desktop-auth=')){void mountDesktopAuth()}else if(location.hash.startsWith('#activate=')){void start('obra')}else if(location.hash.startsWith('#gestao')){void start('gestao')}else if(location.hash.startsWith('#obra')){void start('obra')}else{void import('./portal').then(m=>m.mountMhPortal())}
